### ISSUE TITLE
CSV Import broken on macOS

### ISSUE THREAD

**Issue by maxmunzel** [ananas-analytics/ananas-desktop#63]
Hi Everyone,

I wanted to try out your software but the CSV import is not working on macOS. Im working with a dump of a sqlite3 db (comma separated, utf8 with special characters). I can create the input node, but after dragging in the file, no data shows up and clicking the "Update" button doesn't do anything.

Im happy to provide further information as needed.

**Comment by maxmunzel** [comment]
My Setup:
<img width="698" alt="Screenshot 2019-07-23 at 10 28 10" src="https://user-images.githubusercontent.com/5411096/61696014-cfef9380-ad34-11e9-81e9-5d3914a328a2.png">
Im using the current version, downloaded today from the official website.

**Comment by bhou** [comment]
@maxmunzel Is it possible to provide a small CSV sample file so that I can reproduce it on my side?

**Comment by maxmunzel** [comment]
Thanks for the quick reply!

I created a csv source node, dragged the file in the file text field, pressed "Update" and then "Explore".

The only thing that happenes now is a red "Failed to get data [new line] null"-popup spawning in the bottom left.

My Test File:
https://gist.github.com/maxmunzel/5ba22c68e240e184dae4a79d31136124

**Comment by bhou** [comment]
I can reproduce this issue, it is now fixed in release 0.8.2 https://github.com/ananas-analytics/ananas-desktop/releases/tag/v0.8.2

**Comment by bhou** [comment]
@maxmunzel could you please download version 0.8.2 (https://ananasanalytics.com/docs/downloads/v0.8.2) and see if it helps?

**Comment by maxmunzel** [comment]
@bhou thanks for the quick reaction. I downloaded the version you linked, but sadly the error persists. To rule out some usage error from my side, I did a small screen recording: 
https://www.icloud.com/iclouddrive/0FEp_FZhL74Wjb7oMmhsksYtQ#Screen_Recording480

<img width="396" alt="Screenshot 2019-07-24 at 09 18 38" src="https://user-images.githubusercontent.com/5411096/61773510-27edcf00-adf5-11e9-931e-3f42ed8bedce.png">

**Comment by bhou** [comment]
@maxmunzel  I can't reproduce the issue with 0.8.2 following your recorded video instruction

But I think the issue you are facing is due to a 0.8.1 `ananas` process still running. Please go to Activity Monitor and force quit the `ananas` process, and rerun 0.8.2

<img width="815" alt="Screenshot 2019-07-24 at 10 41 05" src="https://user-images.githubusercontent.com/2302370/61778712-90da4480-adff-11e9-9244-56e44d5da63d.png">

The reason that `ananas` process is still running here, is because Ananas is designed for both small data analysis and big data analysis. In big data case,  jobs could last hours,  we need to keep the process running to support such long-run job (We have jobs on production processing terabytes data in half-hour). 

The issue you are facing does remind me to rethink the way we handle the app quit event. Probably only keep the ananas process when there are jobs running.

**Comment by maxmunzel** [comment]
That resolved it. Thanks again for the quick and helpful reaction!

Have a nice day :)
